# fly.toml app configuration file generated for fastpast-app on 2025-12-18T13:39:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastpast'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  NODE_ENV = 'production'
  PRIMARY_REGION = 'cdg'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  concurrency = { type = "requests", soft_limit = 10, hard_limit = 20 }
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
